spring:
  application:
    name: Caritra Backend
  datasource:
    url: jdbc:postgresql://localhost:5431/Caritra
    username: postgres
    password: Caritra
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:7095/oauth2/

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
