/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "Caritra-Backend"

fun includeSubDirModules(parentName: String, name: String, rename: Boolean) {
    File(rootProject.buildFile.parent, "$parentName/$name").listFiles()?.forEach {
        if (it.isDirectory) {
            logger.info("Added modules: $parentName/$name/${it.name}")
            settings.include("$parentName/$name/${it.name}")
            if (rename) {
                settings.project(":$parentName/$name/${it.name}").name = it.name
            } else {
                settings.project(":$parentName/$name/${it.name}").name = "$name-${it.name}"
            }
        }
    }
}

includeSubDirModules("application", "libs", true)
includeSubDirModules("application", "modules", false)
includeSubDirModules("application", "controllers", false)
includeSubDirModules("application", "services", false)
includeSubDirModules("application", "apps", false)
